In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
XYZ_DF=pd.read_csv(r'D:\Group project\python\XYZCorp_LendingData.txt',header=0,
                      delimiter="\t", low_memory=False)


XYZ_DF.shape   #(855969, 73)
XYZ_DF.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,default_ind
0,1077501,1296599,5000.0,5000.0,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,n,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,1.0,NaN,NaN,3.0,0.0,13648.0,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-2015,171.62,NaN,Jan-2016,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1077430,1314167,2500.0,2500.0,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,n,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-1999,5.0,NaN,NaN,3.0,0.0,1687.0,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-2013,119.66,NaN,Sep-2013,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,1077175,1313524,2400.0,2400.0,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,n,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,2.0,NaN,NaN,2.0,0.0,2956.0,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-2014,649.91,NaN,Jan-2016,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1076863,1277178,10000.0,10000.0,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-2011,n,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-1996,1.0,35.0,NaN,10.0,0.0,5598.0,21.0,37.0,f,0.0,0.0,12226.302212,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-2015,357.48,NaN,Jan-2015,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1075358,1311748,3000.0,3000.0,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-2011,n,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-1996,0.0,38.0,NaN,15.0,0.0,27783.0,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-2016,67.79,Feb-2016,Jan-2016,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [3]:
#Creating copy of original data frame to go ahead for data preprocessing
XYZ_DF_rev=pd.DataFrame.copy(XYZ_DF)
XYZ_DF_rev.shape #(855969, 73)

(855969, 73)

In [4]:
#Feature Selection
# Out of 73 , few variables are not helpful or impactful in order to build a predictive model, hence dropping
XYZ_DF_rev.drop(['id','member_id','funded_amnt_inv','grade','emp_title','pymnt_plan','desc','title',
            'inq_last_6mths','mths_since_last_record','initial_list_status','mths_since_last_major_derog','policy_code',
            'dti_joint','verification_status_joint','tot_coll_amt','tot_cur_bal','open_acc_6m','open_il_6m','open_il_12m'
            ,'open_il_24m','mths_since_rcnt_il','total_bal_il','il_util','open_rv_12m','open_rv_24m',
            'max_bal_bc','all_util','inq_fi','total_cu_tl','inq_last_12m'],axis=1,inplace=True)

XYZ_DF_rev.shape #(855969, 42)
print(XYZ_DF_rev.head())

XYZ_DF_rev1=pd.DataFrame.copy(XYZ_DF_rev)

   loan_amnt  funded_amnt        term  int_rate  installment sub_grade  \
0     5000.0       5000.0   36 months     10.65       162.87        B2
1     2500.0       2500.0   60 months     15.27        59.83        C4
2     2400.0       2400.0   36 months     15.96        84.33        C5
3    10000.0      10000.0   36 months     13.49       339.31        C1
4     3000.0       3000.0   60 months     12.69        67.79        B5

  emp_length home_ownership  annual_inc verification_status   issue_d  \
0  10+ years           RENT     24000.0            Verified  Dec-2011
1   < 1 year           RENT     30000.0     Source Verified  Dec-2011
2  10+ years           RENT     12252.0        Not Verified  Dec-2011
3  10+ years           RENT     49200.0     Source Verified  Dec-2011
4     1 year           RENT     80000.0     Source Verified  Dec-2011

          purpose zip_code addr_state    dti  delinq_2yrs earliest_cr_line  \
0     credit_card    860xx         AZ  27.65          0.0         Jan-1985
1             car    309xx         GA   1.00          0.0         Apr-1999
2  small_business    606xx         IL   8.72          0.0         Nov-2001
3           other    917xx         CA  20.00          0.0         Feb-1996
4           other    972xx         OR  17.94          0.0         Jan-1996

   mths_since_last_delinq  open_acc  pub_rec  revol_bal  revol_util  \
0                     NaN       3.0      0.0    13648.0        83.7
1                     NaN       3.0      0.0     1687.0         9.4
2                     NaN       2.0      0.0     2956.0        98.5
3                    35.0      10.0      0.0     5598.0        21.0
4                    38.0      15.0      0.0    27783.0        53.9

   total_acc  out_prncp  out_prncp_inv   total_pymnt  total_pymnt_inv  \
0        9.0        0.0            0.0   5861.071414          5831.78
1        4.0        0.0            0.0   1008.710000          1008.71
2       10.0        0.0            0.0   3003.653644          3003.65
3       37.0        0.0            0.0  12226.302212         12226.30
4       38.0      766.9          766.9   3242.170000          3242.17

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0          5000.00         861.07                0.00        0.00
1           456.46         435.17                0.00      117.08
2          2400.00         603.65                0.00        0.00
3         10000.00        2209.33               16.97        0.00
4          2233.10        1009.07                0.00        0.00

   collection_recovery_fee last_pymnt_d  last_pymnt_amnt next_pymnt_d  \
0                     0.00     Jan-2015           171.62          NaN
1                     1.11     Apr-2013           119.66          NaN
2                     0.00     Jun-2014           649.91          NaN
3                     0.00     Jan-2015           357.48          NaN
4                     0.00     Jan-2016            67.79     Feb-2016

  last_credit_pull_d  collections_12_mths_ex_med application_type  \
0           Jan-2016                         0.0       INDIVIDUAL
1           Sep-2013                         0.0       INDIVIDUAL
2           Jan-2016                         0.0       INDIVIDUAL
3           Jan-2015                         0.0       INDIVIDUAL
4           Jan-2016                         0.0       INDIVIDUAL

   annual_inc_joint  acc_now_delinq  total_rev_hi_lim  default_ind
0               NaN             0.0               NaN            0
1               NaN             0.0               NaN            1
2               NaN             0.0               NaN            0
3               NaN             0.0               NaN            0
4               NaN             0.0               NaN            0

In [5]:
# Checking if missing values are present.
XYZ_DF_rev.isnull().sum()
print(XYZ_DF_rev.dtypes)

loan_amnt                     float64
funded_amnt                   float64
term                           object
int_rate                      float64
installment                   float64
sub_grade                      object
emp_length                     object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                        object
purpose                        object
zip_code                       object
addr_state                     object
dti                           float64
delinq_2yrs                   float64
earliest_cr_line               object
mths_since_last_delinq        float64
open_acc                      float64
pub_rec                       float64
revol_bal                     float64
revol_util                    float64
total_acc                     float64
out_prncp                     float64
out_prncp_inv                 float64
total_pymnt                   float64
total_pymnt_inv               float64
total_rec_prncp               float64
total_rec_int                 float64
total_rec_late_fee            float64
recoveries                    float64
collection_recovery_fee       float64
last_pymnt_d                   object
last_pymnt_amnt               float64
next_pymnt_d                   object
last_credit_pull_d             object
collections_12_mths_ex_med    float64
application_type               object
annual_inc_joint              float64
acc_now_delinq                float64
total_rev_hi_lim              float64
default_ind                     int64
dtype: object

In [6]:
# Imputing categorical missing data with mode value

colname1=['term','sub_grade','emp_length','home_ownership','verification_status',
          'issue_d','purpose','zip_code','earliest_cr_line','last_pymnt_d',
          'next_pymnt_d','last_credit_pull_d','addr_state']
for x in colname1[:]:
    XYZ_DF_rev[x].fillna(XYZ_DF_rev[x].mode()[0],inplace=True)
    
XYZ_DF_rev.isnull().sum()

loan_amnt                          0
funded_amnt                        0
term                               0
int_rate                           0
installment                        0
sub_grade                          0
emp_length                         0
home_ownership                     0
annual_inc                         0
verification_status                0
issue_d                            0
purpose                            0
zip_code                           0
addr_state                         0
dti                                0
delinq_2yrs                        0
earliest_cr_line                   0
mths_since_last_delinq        439812
open_acc                           0
pub_rec                            0
revol_bal                          0
revol_util                       446
total_acc                          0
out_prncp                          0
out_prncp_inv                      0
total_pymnt                        0
total_pymnt_inv                    0
total_rec_prncp                    0
total_rec_int                      0
total_rec_late_fee                 0
recoveries                         0
collection_recovery_fee            0
last_pymnt_d                       0
last_pymnt_amnt                    0
next_pymnt_d                       0
last_credit_pull_d                 0
collections_12_mths_ex_med        56
application_type                   0
annual_inc_joint              855527
acc_now_delinq                     0
total_rev_hi_lim               67313
default_ind                        0
dtype: int64

In [7]:
#Imputing missing data for Numerical variable with mean value / Zeros
XYZ_DF_rev['annual_inc_joint'].fillna(0,inplace=True)

colname2=['mths_since_last_delinq','revol_util','collections_12_mths_ex_med',
          'total_rev_hi_lim']
for x in colname2[:]:
    XYZ_DF_rev[x].fillna(XYZ_DF_rev[x].mean(),inplace=True)
    
XYZ_DF_rev.isnull().sum()
XYZ_DF_rev.shape   #(855969, 42)

(855969, 42)

In [8]:
#Label Encoding - to label all categorical variable value with numeric value
#Label will get assigned in Ascending alphabetical of variable value

colname1=['term','sub_grade','emp_length','home_ownership','verification_status',
          'purpose','zip_code','earliest_cr_line','last_pymnt_d',
          'next_pymnt_d','last_credit_pull_d','application_type','addr_state']

from sklearn import preprocessing

le={}

for x in colname1:
     le[x]=preprocessing.LabelEncoder()

for x in colname1:
     XYZ_DF_rev[x]=le[x].fit_transform(XYZ_DF_rev[x])
     
XYZ_DF_rev.head()

,loan_amnt,funded_amnt,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,purpose,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,application_type,annual_inc_joint,acc_now_delinq,total_rev_hi_lim,default_ind
0,5000.0,5000.0,0,10.65,162.87,6,1,5,24000.0,2,Dec-2011,1,805,3,27.65,0.0,263,34.149943,3.0,0.0,13648.0,83.7,9.0,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,39,171.62,0,41,0.0,0,0.0,0.0,32163.574526,0
1,2500.0,2500.0,1,15.27,59.83,13,10,5,30000.0,1,Dec-2011,0,295,10,1.00,0.0,41,34.149943,3.0,0.0,1687.0,9.4,4.0,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,5,119.66,0,99,0.0,0,0.0,0.0,32163.574526,1
2,2400.0,2400.0,0,15.96,84.33,14,1,5,12252.0,0,Dec-2011,11,568,14,8.72,0.0,570,34.149943,2.0,0.0,2956.0,98.5,10.0,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,55,649.91,0,41,0.0,0,0.0,0.0,32163.574526,0
3,10000.0,10000.0,0,13.49,339.31,10,1,5,49200.0,1,Dec-2011,9,851,4,20.00,0.0,208,35.000000,10.0,0.0,5598.0,21.0,37.0,0.0,0.0,12226.302212,12226.30,10000.00,2209.33,16.97,0.00,0.00,39,357.48,0,40,0.0,0,0.0,0.0,32163.574526,0
4,3000.0,3000.0,1,12.69,67.79,9,0,5,80000.0,1,Dec-2011,9,904,37,17.94,0.0,274,38.000000,15.0,0.0,27783.0,53.9,38.0,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,40,67.79,0,41,0.0,0,0.0,0.0,32163.574526,0

In [9]:
#Train and Test split

XYZ_DF_rev.issue_d = pd.to_datetime(XYZ_DF_rev.issue_d)   #%y-%m-%d
XYZ_DF_rev1.issue_d = pd.to_datetime(XYZ_DF_rev1.issue_d)

#split data in train and test on the basis of issue_d
split_date = "2015-05-01"

XYZ_training = XYZ_DF_rev.loc[XYZ_DF_rev['issue_d'] <= split_date]
XYZ_training=XYZ_training.drop(['issue_d'],axis=1)
XYZ_training.head()
XYZ_training.shape    #(598978, 41)

XYZ_test = XYZ_DF_rev.loc[XYZ_DF_rev['issue_d'] > split_date]
XYZ_test=XYZ_test.drop(['issue_d'],axis=1)
XYZ_test.head()
XYZ_test.shape  #(256991, 41)

#Exporting Train and Test dataframes to a CSV file for future purpose
XYZ_training_rev1 = XYZ_DF_rev1.loc[XYZ_DF_rev1['issue_d'] <= split_date]
XYZ_training_rev1=XYZ_training_rev1.drop(['issue_d'],axis=1)
XYZ_training_rev1.shape    #(598978, 41)
XYZ_training_rev1.to_csv(r'C:\Users\user\Final_train_rev.csv')

XYZ_test_rev1 = XYZ_DF_rev1.loc[XYZ_DF_rev1['issue_d'] > split_date]
XYZ_test_rev1=XYZ_test_rev1.drop(['issue_d'],axis=1)
XYZ_test_rev1.shape  #(256991, 41)
XYZ_test_rev1.to_csv(r'C:\Users\user\Final_test_rev.csv')

In [10]:
#selecting X and Y

X_train=XYZ_training.values[:,:-1]
Y_train=XYZ_training.values[:,-1]
Y_train=Y_train.astype(int)
print(Y_train)

X_test=XYZ_test.values[:,:-1]
Y_test=XYZ_test.values[:,-1]
Y_test=Y_test.astype(int)
print(Y_test)

[0 1 0 ..., 0 0 0]
[0 0 0 ..., 0 0 0]

In [11]:
#all reg module includes in sklearn.linear_model
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
colname=XYZ_DF_rev.columns[:]
#fitting training data to the model
classifier.fit(X_train,Y_train)
#prediction
Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

#________________________Checking predictions____________________________________
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion_matrix
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)       # Type 2(63) , Type 1(40)
#classification_report
print("Classification report: ")
print(classification_report(Y_test,Y_pred))
#accuracy_score
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)    # 0.999599207754

[[256640     40]
 [    63    248]]
Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00    256680
          1       0.86      0.80      0.83       311

avg / total       1.00      1.00      1.00    256991

Accuracy of the model:  0.999599207754

In [12]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier()
model_DecisionTree.fit(X_train,Y_train)

#fit the model on the data and predict the values
Y_pred=model_DecisionTree.predict(X_test)

#________________________Checking predictions____________________________________
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion_matrix
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)     # Type 2(9) , Type 1(5963)
#classification_report
print("Classification report: ")
print(classification_report(Y_test,Y_pred))
#accuracy_score
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)    #0.976761832126

[[250713   5967]
 [     9    302]]
Classification report:
             precision    recall  f1-score   support

          0       1.00      0.98      0.99    256680
          1       0.05      0.97      0.09       311

avg / total       1.00      0.98      0.99    256991

Accuracy of the model:  0.976746267379

In [13]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=(AdaBoostClassifier(base_estimator=LogisticRegression(),n_estimators=10))

#base_estimator= specify algo
#n_estimators= by default 50
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)

Y_pred=model_AdaBoost.predict(X_test)

#________________________Checking predictions____________________________________

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion_matrix
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)         # Type 2(62) , Type 1(2639)
#classification_report
print("Classification report: ")
print(classification_report(Y_test,Y_pred))
#accuracy_score
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)   #0.989489904316

[[254041   2639]
 [    62    249]]
Classification report:
             precision    recall  f1-score   support

          0       1.00      0.99      0.99    256680
          1       0.09      0.80      0.16       311

avg / total       1.00      0.99      0.99    256991

Accuracy of the model:  0.989489904316

In [14]:
#predicting using the Gradient_Boosting_Classifier
from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier()
#model_GradientBoosting=DecisionTreeClassifier()

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)

Y_pred=model_GradientBoosting.predict(X_test)

#________________________Checking predictions____________________________________

from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion_matrix
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)         # Type 2(10) , Type 1(55)
#classification_report
print("Classification report: ")
print(classification_report(Y_test,Y_pred))
#accuracy_score
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)      #0.999747072855

[[256625     55]
 [    10    301]]
Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00    256680
          1       0.85      0.97      0.90       311

avg / total       1.00      1.00      1.00    256991

Accuracy of the model:  0.999747072855

In [15]:
#Since Gradient Boosting Classifier give us the best prediction we will Append Y_Pred to Test Data
Y_pred_col=list(Y_pred)
XYZ_test_rev1["Y_predictions"]=Y_pred_col
XYZ_test_rev1.head()

XYZ_test_rev1.to_csv(r'C:\Users\user\test_Pred_rev.csv')